In [28]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [82]:
df = pd.read_csv('master_clean_car_make_latest.csv')

## Tires & Wheels Function

In [105]:
# Code for Reproduceability

def tires_wheels_clustering(dataset):
  """
  This code returns the clusters under the category of Tires & Wheels.
  """
  
  dataset = dataset.loc[(dataset['Service Category'] == 'Tires & Wheels'),:]

  # Replace Mount to Mount, Install, & Balance
  dataset.loc[dataset['Service Package'].str.contains('Mount', case = False),'Service Package'] = 'Mount, Install, & Balance'
  dataset.loc[dataset['Service Package'].str.contains('Balance'),'Service Package'] = 'Mount, Install, & Balance'
  dataset.loc[dataset['Service Package'].str.contains('Balancing', case = False),'Service Package'] = 'Mount, Install, & Balance'

  # Map Tire Replacement to all values that contain replacement
  dataset.loc[dataset['Service Package'].str.contains('Replace'),'Service Package'] = 'Tire Replacement'
  dataset.loc[dataset['Service Package'].str.contains('REPLACEMENT', case = False),'Service Package'] = 'Tire Replacement'

  # Tire Vulcanizing
  dataset.loc[dataset['Service Package'].str.contains('Vulcan'),'Service Package'] = 'Tire Vulcanizing'

  # Tire Rotation
  dataset.loc[dataset['Service Package'].str.contains('Rotat'),'Service Package'] = 'Tire Rotation'

  # Other General Services
  dataset.loc[~dataset['Service Package'].isin(['Mount, Install, & Balance','Tire Rotation','Tire Vulcanizing','Tire Replacement']),'Service Package'] = 'Other General Services'
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())
  
tires_wheels_clustering(df)

                           Service Package
Mount, Install, & Balance              777
Other General Services                  55
Tire Vulcanizing                        49
Tire Replacement                        45
Tire Rotation                           30

## Accessories Function

In [91]:
def accessories(dataset):
  """
  This code returns the clusters under the category of Accessories.
  """
  
  
  ## Filter only accessories category
  dataset = dataset.loc[(dataset['Service Category'] == 'Accessories (Gauges, Power Accessories, Vision & Air Bag)'),:]
  
  ## Windshield related services
  dataset.loc[dataset['Service Package'].str.contains('wiper', case = False),'Service Package'] = 'Windshield Wiper Servicing'
  dataset.loc[dataset['Service Package'].str.contains('wind', case = False),'Service Package'] = 'Windshield Wiper Servicing'
  
  ## Door related services
  dataset.loc[dataset['Service Package'].str.contains('door', case = False),'Service Package'] = 'Door Servicing'
  
  ## Window related services
  dataset.loc[dataset['Service Package'].str.contains('window', case = False),'Service Package'] = 'Power Window Servicing'
  
  ## General Services
  dataset.loc[dataset['Service Package'].str.contains('power accessories', case = False),'Service Package'] = 'Power Accessories General Service'
  dataset.loc[dataset['Service Package'].str.contains('general', case = False),'Service Package'] = 'Accessories General Service'
  
  ## Auxilliary Services
  dataset.loc[dataset['Service Package'].str.contains('horn', case = False),'Service Package'] = 'Car Horn Repair & Services'
  dataset.loc[dataset['Service Package'].str.contains('seat', case = False),'Service Package'] = 'Car Seat Services'
  dataset.loc[dataset['Service Package'].str.contains('Hood', case = False),'Service Package'] = 'Car Hood Services'
  
  ## Other Services
  dataset.loc[~dataset['Service Package'].isin(['Windshield Wiper Servicing','Door Servicing','Power Window Servicing','Power Accessories General Service'
                                             ,'Accessories General Service','Car Horn Repair & Services',
                                             'Car Seat Services','Car Hood Services']),'Service Package'] = 'Other Accessories Services'
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

accessories(df)

                             Service Package
Windshield Wiper Servicing               169
Other Accessories Services               123
Door Servicing                            77
Accessories General Service               32
Car Horn Repair & Services                27
Car Hood Services                         24
Car Seat Services                          3

## Batteries Function

In [97]:
def batteries(dataset):
  """
  This code returns the clusters under the category of Batteries.
  """
  
  # Filter only the batteries category
  dataset = dataset.loc[(dataset['Service Category'] == 'Batteries'),:]
  
  # Clustering of Battery Replacement
  dataset.loc[dataset['Service Package'].str.contains('replace', case = False),'Service Package'] = 'Battery Replacement'
  dataset.loc[dataset['Service Package'].str.contains('change', case = False),'Service Package'] = 'Battery Replacement'

  # Clustering of General Battery Services
  dataset.loc[dataset['Service Package'].str.contains('jump', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'
  dataset.loc[dataset['Service Package'].str.contains('charge', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'
  dataset.loc[dataset['Service Package'].str.contains('start', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'
  dataset.loc[dataset['Service Package'].str.contains('test', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'
  dataset.loc[dataset['Service Package'].str.contains('general', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'
  dataset.loc[dataset['Service Package'].str.contains('service', case = False),'Service Package'] = 'Battery General Services (Charge, Test, Start)'

  # Clustering of Other Services as recommended by the Preventive Maintenance Schedule
  dataset.loc[~dataset['Service Package'].isin(['Battery Replacement','Battery General Services (Charge, Test, Start)']),'Service Package'] = 'Other Services (PMS Recommendaton)'
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

batteries(df)

                                                Service Package
Battery Replacement                                         148
Battery General Services (Charge, Test, Start)               35
Other Services (PMS Recommendaton)                           24

## Counter Cash Sale Function

In [100]:
def counter_cash_sale(dataset):
  """
  This code returns the clusters under the category of Counter Cash Sale.
  """
  
  # Filter the counter cash sale category
  dataset = dataset.loc[(dataset['Service Category'] == 'Counter / Cash Sale'),:]
  
  # Counter Cash Sale
  dataset.loc[dataset['Service Package'].str.contains('Counter', case = False),'Service Package'] = 'Counter / Cash Sale'
  
  # Tools & Equipments
  dataset.loc[dataset['Service Package'].str.contains('Tools', case = False),'Service Package'] = 'Tools and Equipment'
  
  # Other Requests
  dataset.loc[~dataset['Service Package'].isin(['Counter / Cash Sale','Tools and Equipment']),'Service Package'] = 'Other Requests'
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

counter_cash_sale(df)

                     Service Package
Counter / Cash Sale               57
Other Requests                     5

## HVAC Function

In [102]:
def hvac(dataset):
  """
  This code returns the clusters under the category of HVAC.
  """
  
  # Filter the HVAC category
  dataset = dataset.loc[(dataset['Service Category'] == 'HVAC (Heating, Ventilation & Air Conditioning)'),:]
  
  ## General Services
  dataset.loc[dataset['Service Package'].str.contains('general', case = False),'Service Package'] = 'Air Conditioner General Cleaning Service'
  dataset.loc[dataset['Service Package'].str.contains('vacuum', case = False),'Service Package'] = 'Vacuum/Charging Service'
  dataset.loc[dataset['Service Package'].str.contains('repair', case = False),'Service Package'] = 'Air Conditioner General Repair Service'

  ## Specific Services
  dataset.loc[dataset['Service Package'].str.contains('filter', case = False),'Service Package'] = 'Cabin Air Filter'
  dataset.loc[dataset['Service Package'].str.contains('compressor', case = False),'Service Package'] = 'Air Conditioning Compressor'
  dataset.loc[dataset['Service Package'].str.contains('evaporator', case = False),'Service Package'] = 'Air Conditioner Evaporator'
  dataset.loc[dataset['Service Package'].str.contains('blower', case = False),'Service Package'] = 'Blower Motor Assembly'
  dataset.loc[dataset['Service Package'].str.contains('fan', case = False),'Service Package'] = 'Air Conditioner Fan Motor'

  ## Other Services
  dataset.loc[~dataset['Service Package'].isin(['Air Conditioner General Cleaning Service','Vacuum/Charging Service','Air Conditioning Compressor'
                                               ,'Cabin Air Filter','Air Conditioner General Repair Service',
                                               'Air Conditioner Evaporator','Blower Motor Assembly','Air Conditioner Fan Motor']
                                              ),'Service Package'] = 'Other Air Conditioning Concerns'
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

hvac(df)

                                          Service Package
Air Conditioner General Cleaning Service              863
Vacuum/Charging Service                               387
Air Conditioning Compressor                            73
Other Air Conditioning Concerns                        72
Cabin Air Filter                                       52
Blower Motor Assembly                                  43
Air Conditioner General Repair Service                 39
Air Conditioner Fan Motor                              26
Air Conditioner Evaporator                             12

## Drive Train Function

In [103]:
def drive_train(dataset):
  """
  This code returns the clusters under the category of Drive Train.
  """
  
  ## This is for drive train
  dataset = dataset.loc[(dataset['Service Category'] == 'Drive Train (Final Drive, Transaxle, Differential & Transfer Case)'),:]
  
  ## Clustering of Drive Shaft
  dataset.loc[dataset['Service Package'].str.contains('Drive Shaft', case = False),'Service Package'] = 'Servicing of Drive Shaft'
  dataset.loc[dataset['Service Package'].str.contains('DriveShaft', case = False),'Service Package'] = 'Servicing of Drive Shaft'
  dataset.loc[dataset['Service Package'].str.contains('Oil Seal', case = False),'Service Package'] = 'Servicing of Drive Shaft'
  dataset.loc[dataset['Service Package'].str.contains('oilseal', case = False),'Service Package'] = 'Servicing of Drive Shaft'

  ## Clustering of Differential Fluid Exchange
  dataset.loc[dataset['Service Package'].str.contains('fluid', case = False),'Service Package'] = 'Differential Fluid Exchange'

  ## Clustering of Axle Shaft
  dataset.loc[dataset['Service Package'].str.contains('Axle', case = False),'Service Package'] = 'Servicing of Axle Shaft'

  ## Other Drive Train Services
  dataset.loc[~dataset['Service Package'].isin(['Servicing of Drive Shaft','Servicing of Axle Shaft','Differential Fluid Exchange']),'Service Package'] = 'Other General Drive Train Services'
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

drive_train(df)

                                    Service Package
Servicing of Drive Shaft                        130
Servicing of Axle Shaft                          38
Differential Fluid Exchange                      33
Other General Drive Train Services               32

## Sublet & Towing Function

In [107]:
def sublet(dataset):
  
  """
  This code returns the clusters under the category of Sublet & Towing.
  """
  
  ## This is for drive train
  dataset = dataset.loc[(dataset['Service Category'] == 'Sublet & Towing'),:]
  
  # Body repair and paint works
  dataset.loc[dataset['Service Package'].str.contains('repair', case = False),'Service Package'] = 'Body Repair and Paint Works'
  
  # Towing
  dataset.loc[dataset['Service Package'].str.contains('towing', case = False),'Service Package'] = 'Towing'
  
  # Other services
  dataset.loc[~dataset['Service Package'].isin(['Body Repair and Paint Works','Towing']),'Service Package'] = 'Other Sublet Services (Machine Shop)'

  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

sublet(df)

                                      Service Package
Body Repair and Paint Works                        33
Other Sublet Services (Machine Shop)               27
Towing                                             19

## Car Brake Function

In [112]:
def brake(dataset):
  dataset = dataset.loc[(dataset['Service Category'] == 'Brakes'),:]
  
  # Disc Brake
  
  dataset.loc[dataset['Service Package'].str.contains('pad', case = False),'Service Package'] = 'Disc Brake Pad'
  dataset.loc[dataset['Service Package'].str.contains('general', case = False),'Service Package'] = 'Brake System General Service'
  dataset.loc[dataset['Service Package'].str.contains('disc brake rotors', case = False),'Service Package'] = 'Disc Brake Rotors'
  dataset.loc[dataset['Service Package'].str.contains('disc brake caliper', case = False),'Service Package'] = 'Disc Brake Caliper'
  dataset.loc[dataset['Service Package'].str.contains('disc brake hardware kit', case = False),'Service Package'] = 'Disc Brake Hardware'
  dataset.loc[dataset['Service Package'].str.contains('disc brake service', case = False),'Service Package'] = 'Disc Brake Hardware'
  dataset.loc[dataset['Service Package'].str.contains('caliper', case = False),'Service Package'] = 'Disc Brake Caliper'
  
  # Drum Brake
  dataset.loc[dataset['Service Package'].str.contains('brake wheel', case = False),'Service Package'] = 'Drum Brake Wheel'
  dataset.loc[dataset['Service Package'].str.contains('shoes', case = False),'Service Package'] = 'Drum Brake Shoes'

  # Brake Fluid and General Services
  dataset.loc[dataset['Service Package'].str.contains('bearing', case = False),'Service Package'] = 'Wheel Bearing'
  dataset.loc[dataset['Service Package'].str.contains('fluid', case = False),'Service Package'] = 'Brake Fluid Service (Exchange, System Flush, Bleeding)'
  dataset.loc[dataset['Service Package'].str.contains('clean', case = False),'Service Package'] = 'Brake Cleaning Service'
  dataset.loc[dataset['Service Package'].str.contains('cylinder', case = False),'Service Package'] = 'Brake Master Cylinder'
  dataset.loc[dataset['Service Package'].str.contains('light', case = False),'Service Package'] = 'Brake Light System'
  dataset.loc[dataset['Service Package'].str.contains('recommend', case = False),'Service Package'] = 'Preventive Maintenance System Recommendation'
  dataset.loc[dataset['Service Package'].str.contains('bleed', case = False),'Service Package'] = 'Brake Fluid Service (Exchange, System Flush, Bleeding)'
  dataset.loc[dataset['Service Package'].str.contains('brake system', case = False),'Service Package'] = 'Brake System General Service'
  dataset.loc[dataset['Service Package'].str.contains('sensor', case = False),'Service Package'] = 'ABS Wheel Speed Sensor'
  
  # Other Brake Services
  dataset.loc[~dataset['Service Package'].isin(['Disc Brake Pad','Brake System General Service','Disc Brake Rotors',
                                                   'Disc Brake Caliper','Drum Brake Wheel',
                                                   'Wheel Bearing','Brake Fluid Service (Exchange, System Flush, Bleeding)',
                                                   'Brake Cleaning Service','Drum Brake Shoes','Brake Master Cylinder',
                                                   'Brake Light System','Preventive Maintenance System Recommendation',
                                                   ]),'Service Package'] = 'Other Brake Services'
  
  
  df.update(dataset)
  
  return(dataset['Service Package'].value_counts().to_frame())

brake(df)

                                                    Service Package
Disc Brake Pad                                                  671
Wheel Bearing                                                   233
Brake System General Service                                    228
Disc Brake Caliper                                              130
Drum Brake Wheel                                                117
Brake Cleaning Service                                          111
Brake Fluid Service (Exchange, System Flush, Bl...              104
Disc Brake Rotors                                               100
Other Brake Services                                             93
Brake Master Cylinder                                            44
Preventive Maintenance System Recommendation                     35
Drum Brake Shoes                                                 32
Brake Light System                                               25

In [113]:
df.loc[(df['Service Category'] == 'Brakes'),:]

,Created,Year,Work Order,Mileage In,Make,Model,Service Category,Service Package,Description,Net Total,ServiceItemID,ContactID,InvoiceID,Line Type
55,2019-01-03 08:51:12,2012.0,99.0,61487.0,nissan,XTRAIL,Brakes,Wheel Bearing,Labor,2178.58,3bc3be5b-e17b-432b-bc84-89e8d1996d33,3c536d5d-4c80-4dce-ad8b-549e444d388c,e6657a5f-699c-4546-82cd-f4902474d635,Labor
57,2019-01-03 08:51:12,2012.0,99.0,61487.0,nissan,XTRAIL,Brakes,Wheel Bearing,FRONT WHEEL BEARING (NTN BEARING),8000.00,3bc3be5b-e17b-432b-bc84-89e8d1996d33,3c536d5d-4c80-4dce-ad8b-549e444d388c,e6657a5f-699c-4546-82cd-f4902474d635,Material
68,2019-01-04 08:40:01,2013.0,117.0,48238.0,toyota,SUPER GRANDIA,Brakes,Brake System General Service,BRAKE CLEANER 14oz,145.00,b2e171a3-27e0-4269-9c28-7dd0a23631ab,4c30efe4-5e5e-456c-a875-086bb912c2b4,396eb186-c6b4-4101-89d7-589391143fe7,Material
69,2019-01-04 08:40:01,2013.0,117.0,48238.0,toyota,SUPER GRANDIA,Brakes,Disc Brake Pad,Disc Brake Pad frt,2181.82,b2e171a3-27e0-4269-9c28-7dd0a23631ab,4c30efe4-5e5e-456c-a875-086bb912c2b4,396eb186-c6b4-4101-89d7-589391143fe7,Material
70,2019-01-04 08:40:01,2013.0,117.0,48238.0,toyota,SUPER GRANDIA,Brakes,Disc Brake Pad,Labor,1116.08,b2e171a3-27e0-4269-9c28-7dd0a23631ab,4c30efe4-5e5e-456c-a875-086bb912c2b4,396eb186-c6b4-4101-89d7-589391143fe7,Labor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40927,08/01/2020 11:36,2014.0,491.0,148450.0,toyota,VIOS,Brakes,Disc Brake Pad,BRAKE FLUID PRESTONE,207.51,daf511d3-7db4-49b0-9c27-64ca0400a10d,49832654-8201-46a1-8332-b020426842c1,a5cc5531-e928-436f-a865-4f7c8e65dce9,Material
40931,29/02/2020 10:25,0.0,714.0,356571.0,mitsubishi,L300,Brakes,Drum Brake Shoes,Labor,1339.29,994810bf-c329-4ae6-8bba-d19789648ba8,0a3293b8-de75-4c89-9bd0-f6e50618771b,eea72de3-0a10-40fe-b39a-594235bbd735,Labor
40932,29/02/2020 10:25,0.0,714.0,356571.0,mitsubishi,L300,Brakes,Drum Brake Shoes,BRAKE SHOE L300 REAR,1820.00,994810bf-c329-4ae6-8bba-d19789648ba8,0a3293b8-de75-4c89-9bd0-f6e50618771b,eea72de3-0a10-40fe-b39a-594235bbd735,Material
40933,29/02/2020 10:25,0.0,714.0,356571.0,mitsubishi,L300,Brakes,Drum Brake Shoes,WHEEL CYLINDER L300,1305.00,994810bf-c329-4ae6-8bba-d19789648ba8,0a3293b8-de75-4c89-9bd0-f6e50618771b,eea72de3-0a10-40fe-b39a-594235bbd735,Material
40934,29/02/2020 10:25,0.0,714.0,356571.0,mitsubishi,L300,Brakes,Drum Brake Shoes,BRAKE FLUID,500.00,994810bf-c329-4ae6-8bba-d19789648ba8,0a3293b8-de75-4c89-9bd0-f6e50618771b,eea72de3-0a10-40fe-b39a-594235bbd735,Material

In [111]:
df['Service Package'].value_counts().to_frame().head(20)

                                                    Service Package
MINOR Preventive Maintenance Service                           1075
CVI Complete Vehicle Inspection                                1047
Air Conditioner General Cleaning Service                        863
Mount, Install, & Balance                                       777
MINOR PMS                                                       626
MINOR Preventive Maintenance Service (LARGE SUV...              619
MINOR Preventive Maintenance Service (MEDIUM SE...              546
MAJOR PMS                                                       541
MINOR Preventive Maintenance Service (COMPACT/S...              514
MINOR Preventive Maintenance Service (SMALL SUV...              483
VPX - Change Oil Package - (GAS)                                423
 Maintenance General Service (PMS Recommendations)              394
Vacuum/Charging Service                                         387
MAJOR Preventive Maintenance Service                            349
VPX - Change Oil Package - (DIESEL)                             330
MINOR Preventive Maintenance Service                            320
Complete Computerized Wheel Alignment (SUV & PI...              288
MAJOR Preventive Maintenance Service / COMPLETE...              286
VALUEPLUS PMS PACKAGE - COMPACT / SMALL SEDAN                   283
Complete Computerized Wheel Alignment (SEDAN)                   269